services:
  napcat:
    image: ${NAPCAT_IMAGE:-mlikiowa/napcat-docker:v4.8.119}
    container_name: napcat
    restart: always
    env_file:
      - ../.env
    mac_address: "ec:4c:8c:e2:ed:20"
    privileged: true
    ports:
      - "3001:3001"
      - "6099:6099"
    environment:
      - TZ=Asia/Shanghai
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
    volumes:
      - ./napcat-entrypoint.custom.sh:/app/entrypoint.sh:ro
      - ~/.config/QQ:/app/.config/QQ
      - ~/napcat/napcat-config:/app/napcat/config
      - ~/napcat/logs:/app/napcat/logs

  napcat_2365524513:
    image: ${NAPCAT_IMAGE:-mlikiowa/napcat-docker:v4.8.119}
    container_name: napcat_2365524513
    restart: always
    env_file:
      - ../.env
    mac_address: "ec:4c:8c:e2:ed:21"
    privileged: true
    ports:
      - "3002:3001"
      - "6100:6099"
    environment:
      - TZ=Asia/Shanghai
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
      - QQ_BOT_UIN=2365524513
      - ACCOUNT=2365524513
    volumes:
      - ./napcat-entrypoint.custom.sh:/app/entrypoint.sh:ro
      - ~/.config/QQ-2365524513:/app/.config/QQ
      - ~/napcat-2365524513/napcat-config:/app/napcat/config
      - ~/napcat-2365524513/logs:/app/napcat/logs
